export const PlantSort = [
  {
    id: "daisy",
    name: "데이지",
    duration: 10,
    length: 12,
    difficulty: 1,
    meanings: ["새로운시작", "순수한마음", "기다림의기쁨"],
    bgColor: "bg-mint-02",
    textColor: "text-green-01",
    img: "/images/garden/daisy",
  },
  {
    id: "tulip",
    name: "튤립",
    duration: 12,
    length: 12,
    difficulty: 2,
    meanings: ["애정", "희망", "행복한사랑"],
    bgColor: "bg-blue-01",
    textColor: "text-blue-00",
    img: "/images/garden/tulip",
  },
  {
    id: "lily",
    name: "은방울꽃",
    duration: 12,
    length: 15,
    difficulty: 2,
    meanings: ["겸손", "순수함", "행복의방문"],
    bgColor: "bg-blue-01",
    textColor: "text-blue-00",
    img: "/images/garden/lily",
  },
  {
    id: "sunflower",
    name: "해바라기",
    duration: 17,
    length: 14,
    difficulty: 4,
    meanings: ["존경", "동경", "사랑의고백"],
    bgColor: "bg-pink-00",
    textColor: "text-red-01",
    img: "/images/garden/sunflower",
  },
  {
    id: "baby-breath",
    name: "안개",
    duration: 19,
    length: 18,
    difficulty: 4,
    meanings: ["배려", "맑은마음", "순수한사랑"],
    bgColor: "bg-pink-00",
    textColor: "text-red-01",
    img: "/images/garden/baby-breath",
  },
];
